/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.crudUnidadDeProducto;

import control.ControlProducto_Unidad;
import control.ControlProducto_aseo;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import modelo.producto_unidad;
import modelo.productos_aseo;

/**
 *
 * @author Juan Diego Tabares
 */
public class vistaInsertarUnidadDeProducto extends javax.swing.JFrame {

    /**
     * Creates new form vistaInsertarUnidadDeProducto
     */
    
    LinkedList<productos_aseo> listaPA; // LISTA PRODUCTO ASEO
    LinkedList<producto_unidad> listaPU; // LISTA PRODUCTO UNIDAD
    int numeroTanda=0;
    public vistaInsertarUnidadDeProducto() {
        initComponents();
        
        listaPA= new LinkedList<>();
        listaPU= new LinkedList<>();
        
        insertar.setVisible(false);
        SpinnerNumberModel sm= new SpinnerNumberModel();
        sm.setMinimum(1);
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        comboDetalle = new javax.swing.JComboBox<>();
        comboProducto = new javax.swing.JComboBox<>();
        fecha = new javax.swing.JTextField();
        agregar = new javax.swing.JButton();
        numero = new javax.swing.JSpinner();
        insertar = new javax.swing.JButton();
        numTanda = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        comboDetalle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Seleccione -" }));
        comboDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDetalleActionPerformed(evt);
            }
        });

        comboProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Seleccione -", " " }));

        agregar.setText("Agregar");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        insertar.setText("Insertar");
        insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarActionPerformed(evt);
            }
        });

        numTanda.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(insertar)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(comboDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(numTanda, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(agregar)
                        .addGap(55, 55, 55))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregar)
                    .addComponent(numTanda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(insertar)
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
     
    
    
    private void comboDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDetalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboDetalleActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        // TODO add your handling code here:
        insertar.setVisible(true);
        int num= (int) numero.getValue();
        
       String item = String.valueOf(comboProducto.getSelectedItem());
        String[] sItem= item.split(" - ");
        int idProducto= Integer.parseInt (sItem[0]);
        
        String item2 = String.valueOf(comboDetalle.getSelectedItem());
        String[] sItem2= item2.split(" - ");
        int idDetalle= Integer.parseInt (sItem2[0]);
        
        
        String fechas= fecha.getText();
        for(int i=0; i<num; i++){
        producto_unidad objpu=new producto_unidad(idProducto, fechas, idDetalle); //NO OLVIDAR MODIFICAR TRAS CREAR LO DE DETALLE !!!!!!!!!!!!!!!
        listaPU.add(objpu);
        }
        
        
        numeroTanda++;
        numTanda.setText(String.valueOf(numeroTanda));
        
        // setea a cero el contador 
        numero.setValue(1);
      
    }//GEN-LAST:event_agregarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        ControlProducto_aseo controlp = new ControlProducto_aseo();

        listaPA= controlp.consultarProducto();

        for (int i = 0; i < listaPA.size(); i++) {
            productos_aseo objetop = listaPA.get(i);
            String item = String.valueOf(objetop.getIdProductoAseo());
            System.out.println(item);
           comboProducto.addItem(item+" - "+objetop.getNombreProductoAseo());
        }
        
        
        //  HACER LO MISMO PARA EL comboDetalle    !!!!!!!!!!!!!!!!!!!!!!!!!!!!
        
        
    }//GEN-LAST:event_formWindowOpened

    private void insertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarActionPerformed
        // TODO add your handling code here:
        
        
        
        ControlProducto_Unidad control=new ControlProducto_Unidad();
        
        boolean rs =control.insertarProductoUnidad(listaPU);
        if(rs){
            JOptionPane.showMessageDialog(rootPane, "Se insertaron exitosamente");
            listaPU.clear();
        }else{
            JOptionPane.showMessageDialog(rootPane, "No se insertaron los datos");
        }
    }//GEN-LAST:event_insertarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaInsertarUnidadDeProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaInsertarUnidadDeProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaInsertarUnidadDeProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaInsertarUnidadDeProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaInsertarUnidadDeProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JComboBox<String> comboDetalle;
    private javax.swing.JComboBox<String> comboProducto;
    private javax.swing.JTextField fecha;
    private javax.swing.JButton insertar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel numTanda;
    private javax.swing.JSpinner numero;
    // End of variables declaration//GEN-END:variables
}
